[project]
name = "qz"
description = "Minimal time tracking CLI app"
readme = "README.md"
license = { file = "UNLICENSE" }
authors = [
  { name = "Tiago Seabra", email = "tlgs@users.noreply.github.com" }
]
dynamic = ["version"]

urls = { Source = "https://github.com/tlgs/qz" }
scripts = { qz = "qz:main" }

[project.optional-dependencies]
dev = [
  "pre-commit",
]


[tool.hatch]
version.source = "vcs"
build.targets.wheel.only-include = ["qz.py"]


[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
